# Created: 2020/10/18 21:23:48
# Last modified: 2020/10/18 21:24:10

name: Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Run marp-action setup
        id: marp-action
        uses: aheil/marp-action@v1.0.0
        with:
          src-dir: 'slides'